version: '2.2'

services:
  http-proxy:
    build:
      context: ./http-proxy-server/
      args:
        http_proxy:
        https_proxy:
    ports:
      - "${HTTP_PROXY_SERVER_BIND_IP_PORT:-127.0.0.1:3128}:3128"
    environment:
      TZ:
    restart: always

  proxy-log:
    build:
      context: ./alpine-tini/
      args:
        http_proxy:
        https_proxy:
    depends_on:
      - http-proxy
    volumes_from:
      - http-proxy
    command: tail -f /var/log/squid/access.log
    logging:
      driver: "json-file"
      options:
        max-size: "10mb"
        max-file: "3"
