version: '3'

services:
  http-proxy:
    build:
      context: ./http-proxy-server/
      args:
        http_proxy:
        https_proxy:
    ports:
      - "${HTTP_PROXY_SERVER_BIND_IP_PORT:-127.0.0.1:3128}:3128"
    environment:
      PROXY_FORWARDING_HOSTNAME: "${PROXY_FORWARDING_HOSTNAME-proxy.example.com}"
      PROXY_FORWARDING_PORT: "${PROXY_FORWARDING_PORT-8080}"
      PROXY_AUTH_USERNAME:
      PROXY_AUTH_PASSWORD:
      TZ:
    restart: always
    dns: 8.8.8.8
    logging:
      driver: "json-file"
      options:
        max-size: "10mb"
        max-file: "3"
